name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # or the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # or the version of Node.js your project needs

    - name: Install dependencies
      run: npm install  # or the command for your static site generator

    - name: Build the project
      run: npm run build  # or the command to build your project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # or the directory where your built files are located
